name: Workflow Commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"
      - name: Setting an debug message with parametes:
        run: echo "::debug title=Debug title, file=app.js, line=2, endLine=3, col=5, endColumn=7::Missing Semicolon:"
      - name: Setting an warning message with parametes:
        run: echo "::warning title=Warning title, file=app.js, line=2, endLine=3, col=5, endColumn=7::Missing Semicolon:"
      - name: Setting an notice message with parametes:
        run: echo "::notice title=Notice title, file=app.js, line=2, endLine=3, col=5, endColumn=7::Missing Semicolon:"

